### ISSUE TITLE
EUMETSAT data visualisation

### ISSUE THREAD

**Issue by vrautenbach** [geo-classroom/daily-rainfall#22]
The styling of the polygons needs to be adjusted. The opacity seems to be a bit too high, thus mostly transparent apart from the lines. I would personally like the stroke and fill to be the same with a slight opacity to be able to see the base map.

**Comment by Riley-5** [comment]
Opacity seems to predominantly change the border instead of the fill of the polygon. Adjusted the weight of the lines to 3 which gives it an appearance of a "fill" until zoomed in. Looking at the documentation there doesn't look like a option to give the polygons an actual fill. Possibly workaround could be ramping up the darkness of the shade of blue for all categories to give the polygon a "fill" like feel. 

What do you think? @vrautenbach

**Comment by vrautenbach** [comment]
Can you maybe create a couple of possible options to choice from? Then we can pick the option that looks best from what is possible?

**Comment by Riley-5** [comment]
will do! Will send some screenshots in a bit
